// Verilog netlist generated by Workcraft 3
// * Workcraft version:  3.5.3
// * Operating system:   Windows 11 amd64
// * Creation timestamp: 2025-12-29T16:53:33.083Z
// * Design title:       VME
// * JavaScript command: framework.exportWork(workspaceEntry, 'vme 4.stg.v', 'Verilog')
module VME (dsr, dsw, ldtack, d, lds, dtack);
    input dsr, dsw, ldtack;
    output d, lds, dtack;
    wire U1_ON, IN_BUBBLE3_ON, U5_ON, IN_BUBBLE8_ON, IN_BUBBLE11_ON, OUT_BUBBLE14_ON, U15_ON, IN_BUBBLE17_ON, IN_BUBBLE19_ON, IN_BUBBLE21_ON, U22_ON;

    NAND3 U1 (.ON(U1_ON), .A(ldtack), .B(U22_ON), .C(dsr));
    // This inverter should have a short delay
    INV IN_BUBBLE3 (.ON(IN_BUBBLE3_ON), .I(OUT_BUBBLE14_ON));
    OAI21 U5 (.ON(U5_ON), .A1(IN_BUBBLE3_ON), .A2(U22_ON), .B(dsw));
    NAND2 U6 (.ON(d), .A(U1_ON), .B(U5_ON));
    // This inverter should have a short delay
    INV IN_BUBBLE8 (.ON(IN_BUBBLE8_ON), .I(dsw));
    AO22 U9 (.O(lds), .A1(IN_BUBBLE8_ON), .A2(U22_ON), .B1(dsw), .B2(OUT_BUBBLE14_ON));
    // This inverter should have a short delay
    INV IN_BUBBLE11 (.ON(IN_BUBBLE11_ON), .I(OUT_BUBBLE14_ON));
    AOI21 U12 (.ON(dtack), .A1(dsw), .A2(d), .B(IN_BUBBLE11_ON));
    INV OUT_BUBBLE14 (.ON(OUT_BUBBLE14_ON), .I(U15_ON));
    AOI222 U15 (.ON(U15_ON), .A1(d), .A2(U22_ON), .B1(OUT_BUBBLE14_ON), .B2(U22_ON), .C1(dsw), .C2(OUT_BUBBLE14_ON));
    // This inverter should have a short delay
    INV IN_BUBBLE17 (.ON(IN_BUBBLE17_ON), .I(dsr));
    // This inverter should have a short delay
    INV IN_BUBBLE19 (.ON(IN_BUBBLE19_ON), .I(d));
    // This inverter should have a short delay
    INV IN_BUBBLE21 (.ON(IN_BUBBLE21_ON), .I(U22_ON));
    AOI222 U22 (.ON(U22_ON), .A1(IN_BUBBLE17_ON), .A2(IN_BUBBLE19_ON), .B1(ldtack), .B2(IN_BUBBLE21_ON), .C1(dsw), .C2(ldtack));

    // signal values at the initial state:
    // IN_BUBBLE11_ON IN_BUBBLE17_ON IN_BUBBLE19_ON IN_BUBBLE21_ON IN_BUBBLE3_ON IN_BUBBLE8_ON !OUT_BUBBLE14_ON U15_ON U1_ON !U22_ON U5_ON !d !dsr !dsw !dtack !lds !ldtack
endmodule
