// Verilog netlist generated by Workcraft 3
// * Workcraft version:  3.5.3
// * Operating system:   Windows 11 amd64
// * Creation timestamp: 2025-12-29T16:51:40.031Z
// * Design title:       VME
// * JavaScript command: framework.exportWork(workspaceEntry, 'vme 1.stg.v', 'Verilog')
module VME (dsr, dsw, ldtack, d, lds, dtack);
    input dsr, dsw, ldtack;
    output d, lds, dtack;
    wire csc, csc1;

    assign #1 d = (~csc | csc1) & dsw | csc1 & ldtack;
    assign #1 lds = (d | dsw) & csc | csc1 & ~dsw;
    assign #1 dtack = (~d | ~dsw) & csc;
    assign #1 csc = (csc | csc1) & (d | dsw);
    assign #1 csc1 = (csc1 | ~ldtack) & dsr | d & ~ldtack;

    // signal values at the initial state:
    // !csc !csc1 !d !dsr !dsw !dtack !lds !ldtack
endmodule
