// Verilog netlist generated by Workcraft 3
// * Workcraft version:  3.5.3
// * Operating system:   Windows 11 amd64
// * Creation timestamp: 2025-12-29T16:53:18.513Z
// * Design title:       VME
// * JavaScript command: framework.exportWork(workspaceEntry, 'vme 3.stg.v', 'Verilog')
module VME (dsr, dsw, ldtack, d, lds, dtack);
    input dsr, dsw, ldtack;
    output d, lds, dtack;
    wire d_SET, d_nRESET, lds_SET, lds_nRESET, csc_SET, csc_nRESET, csc, csc1_SET, csc1_nRESET, csc1;

    assign #1 d_SET = (csc1 & ldtack | dsw) & ~csc;
    assign #1 d_nRESET = ~csc | csc1;
    assign #1 d = d_SET & d_nRESET | d & (d_SET | d_nRESET);
    assign #1 lds_SET = (csc | dsr) & csc1;
    assign #1 lds_nRESET = (d | dsw) & csc | csc1;
    assign #1 lds = lds_SET & lds_nRESET | lds & (lds_SET | lds_nRESET);
    assign #1 dtack = (~d | ~dsw) & csc;
    assign #1 csc_SET = csc1 & d;
    assign #1 csc_nRESET = d | dsw;
    assign #1 csc = csc_SET & csc_nRESET | csc & (csc_SET | csc_nRESET);
    assign #1 csc1_SET = (d | dsr) & ~ldtack;
    assign #1 csc1_nRESET = dsr | ~ldtack;
    assign #1 csc1 = csc1_SET & csc1_nRESET | csc1 & (csc1_SET | csc1_nRESET);

    // signal values at the initial state:
    // !csc !csc1 !csc1_SET csc1_nRESET !csc_SET !csc_nRESET !d !d_SET d_nRESET !dsr !dsw !dtack !lds !lds_SET !lds_nRESET !ldtack
endmodule
