// Verilog netlist generated by Workcraft 3
// * Workcraft version:  3.5.3
// * Operating system:   Windows 11 amd64
// * Creation timestamp: 2025-12-29T16:52:32.571Z
// * Design title:       VME
// * JavaScript command: framework.exportWork(workspaceEntry, 'vme 2.stg.v', 'Verilog')
module VME (dsr, dsw, ldtack, d, lds, dtack);
    input dsr, dsw, ldtack;
    output d, lds, dtack;
    wire csc, csc1;

    assign #1 d = (csc1 & ldtack | dsw) & ~csc | d & (~csc | dsr | ~ldtack);
    assign #1 lds = (csc | dsr) & csc1 | lds & (csc & dsw | csc1);
    assign #1 dtack = (~csc1 | ~dsw) & csc | dtack & (csc);
    assign #1 csc = csc1 & d | csc & (csc1 | dsw);
    assign #1 csc1 = (d | dsr) & ~ldtack | csc1 & (d | dsr);

    // signal values at the initial state:
    // !csc !csc1 !d !dsr !dsw !dtack !lds !ldtack
endmodule
