# STG file generated by Workcraft 3
# * Workcraft version:  3.5.3
# * Operating system:   Windows 11 amd64
# * Creation timestamp: 2025-12-29T16:52:54.998Z
# * Design title:       VME
# * JavaScript command: framework.exportWork(workspaceEntry, 'vme.stg.g', 'STG')
.model VME
.inputs dsr dsw ldtack
.outputs d dtack lds
.graph
d+ dtack+
d+/1 lds+/1
d- p3 p4
d-/1 dtack+/1
dsr+ lds+
dsr- d-
dsw+ d+/1
dsw- p3 p4
dtack+ dsr-
dtack+/1 dsw-
dtack- p1
lds+ ldtack+
lds+/1 ldtack+/1
lds- ldtack-
ldtack+ d+
ldtack+/1 d-/1
ldtack- p2
p1 dsr+ dsw+
p2 lds+ lds+/1
p3 lds-
p4 dtack-
.marking {p1 p2}
.end
