// Verilog netlist generated by Workcraft 3
// * Workcraft version:  3.5.3
// * Operating system:   Windows 11 amd64
// * Creation timestamp: 2025-12-28T17:29:33.571Z
// * Design title:       C_element
// * JavaScript command: framework.exportWork(workspaceEntry, 'celement 6.stg.v', 'Verilog')
module C_element (in1, in2, out);
    input in1, in2;
    output out;

    assign #1 out = (in2 | out) & in1 | in2 & out;

    // signal values at the initial state:
    // !in1 !in2 !out
endmodule
