-- VHDL conversion from Verilog netlist generated by Workcraft 3
-- Original Workcraft version: 3.5.3
-- Design title: VME Stage 1
-- Converted: 2025-12-29

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity VME is
    port (
        dsr    : in  std_logic;
        dsw    : in  std_logic;
        ldtack : in  std_logic;
        d      : out std_logic;
        lds    : out std_logic;
        dtack  : out std_logic
    );
end VME;

architecture stage1 of VME is
    signal csc  : std_logic;
    signal csc1 : std_logic;
begin

    -- All assignments have 1 time unit delay in original Verilog
    d     <= (not csc or csc1) and dsw or csc1 and ldtack after 1 ns;
    lds   <= (d or dsw) and csc or csc1 and not dsw after 1 ns;
    dtack <= (not d or not dsw) and csc after 1 ns;
    csc   <= (csc or csc1) and (d or dsw) after 1 ns;
    csc1  <= (csc1 or not ldtack) and dsr or d and not ldtack after 1 ns;

    -- Initial signal values (for simulation):
    -- csc = '0', csc1 = '0', d = '0', dsr = '0', dsw = '0'
    -- dtack = '0', lds = '0', ldtack = '0'

end stage1;