-- VHDL conversion from Verilog netlist generated by Workcraft 3
-- Original Workcraft version: 3.5.3
-- Design title: VME Stage 2
-- Converted: 2025-12-29

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity VME is
    port (
        dsr    : in  std_logic;
        dsw    : in  std_logic;
        ldtack : in  std_logic;
        d      : out std_logic;
        lds    : out std_logic;
        dtack  : out std_logic
    );
end VME;

architecture stage2 of VME is
    signal csc  : std_logic;
    signal csc1 : std_logic;
begin

    -- All assignments have 1 time unit delay in original Verilog
    d     <= (csc1 and ldtack or dsw) and not csc or d and (not csc or dsr or not ldtack) after 1 ns;
    lds   <= (csc or dsr) and csc1 or lds and (csc and dsw or csc1) after 1 ns;
    dtack <= (not csc1 or not dsw) and csc or dtack and csc after 1 ns;
    csc   <= csc1 and d or csc and (csc1 or dsw) after 1 ns;
    csc1  <= (d or dsr) and not ldtack or csc1 and (d or dsr) after 1 ns;

    -- Initial signal values (for simulation):
    -- csc = '0', csc1 = '0', d = '0', dsr = '0', dsw = '0'
    -- dtack = '0', lds = '0', ldtack = '0'

end stage2;