-- VHDL conversion from Verilog netlist generated by Workcraft 3
-- Original Workcraft version: 3.5.3
-- Design title: VME Stage 3
-- Converted: 2025-12-29

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity VME is
    port (
        dsr    : in  std_logic;
        dsw    : in  std_logic;
        ldtack : in  std_logic;
        d      : out std_logic;
        lds    : out std_logic;
        dtack  : out std_logic
    );
end VME;

architecture stage3 of VME is
    signal d_SET        : std_logic;
    signal d_nRESET     : std_logic;
    signal lds_SET      : std_logic;
    signal lds_nRESET   : std_logic;
    signal csc_SET      : std_logic;
    signal csc_nRESET   : std_logic;
    signal csc          : std_logic;
    signal csc1_SET     : std_logic;
    signal csc1_nRESET  : std_logic;
    signal csc1         : std_logic;
begin

    -- All assignments have 1 time unit delay in original Verilog
    -- SET/RESET logic for d
    d_SET      <= (csc1 and ldtack or dsw) and not csc after 1 ns;
    d_nRESET   <= not csc or csc1 after 1 ns;
    d          <= d_SET and d_nRESET or d and (d_SET or d_nRESET) after 1 ns;
    
    -- SET/RESET logic for lds
    lds_SET    <= (csc or dsr) and csc1 after 1 ns;
    lds_nRESET <= (d or dsw) and csc or csc1 after 1 ns;
    lds        <= lds_SET and lds_nRESET or lds and (lds_SET or lds_nRESET) after 1 ns;
    
    -- dtack (simple combinational logic)
    dtack      <= (not d or not dsw) and csc after 1 ns;
    
    -- SET/RESET logic for csc
    csc_SET    <= csc1 and d after 1 ns;
    csc_nRESET <= d or dsw after 1 ns;
    csc        <= csc_SET and csc_nRESET or csc and (csc_SET or csc_nRESET) after 1 ns;
    
    -- SET/RESET logic for csc1
    csc1_SET    <= (d or dsr) and not ldtack after 1 ns;
    csc1_nRESET <= dsr or not ldtack after 1 ns;
    csc1        <= csc1_SET and csc1_nRESET or csc1 and (csc1_SET or csc1_nRESET) after 1 ns;

    -- Initial signal values (for simulation):
    -- csc = '0', csc1 = '0', csc1_SET = '0', csc1_nRESET = '1'
    -- csc_SET = '0', csc_nRESET = '0', d = '0', d_SET = '0', d_nRESET = '1'
    -- dsr = '0', dsw = '0', dtack = '0', lds = '0', lds_SET = '0'
    -- lds_nRESET = '0', ldtack = '0'

end stage3;