-- VHDL conversion from Verilog netlist generated by Workcraft 3
-- Original Workcraft version: 3.5.3
-- Design title: VME Stage 4 (Gate-level implementation)
-- Converted: 2025-12-29

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

-- Component declarations for standard cells
-- These would typically come from a standard cell library
package gate_components is
    
    component NAND2
        port (
            ON : out std_logic;
            A  : in  std_logic;
            B  : in  std_logic
        );
    end component;
    
    component NAND3
        port (
            ON : out std_logic;
            A  : in  std_logic;
            B  : in  std_logic;
            C  : in  std_logic
        );
    end component;
    
    component INV
        port (
            ON : out std_logic;
            I  : in  std_logic
        );
    end component;
    
    component OAI21  -- OR-AND-Invert: !((A1 + A2) * B)
        port (
            ON : out std_logic;
            A1 : in  std_logic;
            A2 : in  std_logic;
            B  : in  std_logic
        );
    end component;
    
    component AO22  -- AND-OR: (A1*A2) + (B1*B2)
        port (
            O  : out std_logic;
            A1 : in  std_logic;
            A2 : in  std_logic;
            B1 : in  std_logic;
            B2 : in  std_logic
        );
    end component;
    
    component AOI21  -- AND-OR-Invert: !((A1*A2) + B)
        port (
            ON : out std_logic;
            A1 : in  std_logic;
            A2 : in  std_logic;
            B  : in  std_logic
        );
    end component;
    
    component AOI222  -- AND-OR-Invert: !((A1*A2) + (B1*B2) + (C1*C2))
        port (
            ON : out std_logic;
            A1 : in  std_logic;
            A2 : in  std_logic;
            B1 : in  std_logic;
            B2 : in  std_logic;
            C1 : in  std_logic;
            C2 : in  std_logic
        );
    end component;
    
end package gate_components;

-- Gate implementations (behavioral models)
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity NAND2 is
    port (
        ON : out std_logic;
        A  : in  std_logic;
        B  : in  std_logic
    );
end NAND2;

architecture behavioral of NAND2 is
begin
    ON <= not (A and B);
end behavioral;

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity NAND3 is
    port (
        ON : out std_logic;
        A  : in  std_logic;
        B  : in  std_logic;
        C  : in  std_logic
    );
end NAND3;

architecture behavioral of NAND3 is
begin
    ON <= not (A and B and C);
end behavioral;

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity INV is
    port (
        ON : out std_logic;
        I  : in  std_logic
    );
end INV;

architecture behavioral of INV is
begin
    ON <= not I;
end behavioral;

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity OAI21 is
    port (
        ON : out std_logic;
        A1 : in  std_logic;
        A2 : in  std_logic;
        B  : in  std_logic
    );
end OAI21;

architecture behavioral of OAI21 is
begin
    ON <= not ((A1 or A2) and B);
end behavioral;

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity AO22 is
    port (
        O  : out std_logic;
        A1 : in  std_logic;
        A2 : in  std_logic;
        B1 : in  std_logic;
        B2 : in  std_logic
    );
end AO22;

architecture behavioral of AO22 is
begin
    O <= (A1 and A2) or (B1 and B2);
end behavioral;

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity AOI21 is
    port (
        ON : out std_logic;
        A1 : in  std_logic;
        A2 : in  std_logic;
        B  : in  std_logic
    );
end AOI21;

architecture behavioral of AOI21 is
begin
    ON <= not ((A1 and A2) or B);
end behavioral;

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity AOI222 is
    port (
        ON : out std_logic;
        A1 : in  std_logic;
        A2 : in  std_logic;
        B1 : in  std_logic;
        B2 : in  std_logic;
        C1 : in  std_logic;
        C2 : in  std_logic
    );
end AOI222;

architecture behavioral of AOI222 is
begin
    ON <= not ((A1 and A2) or (B1 and B2) or (C1 and C2));
end behavioral;

-- Main VME module using gate-level description
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use work.gate_components.all;

entity VME is
    port (
        dsr    : in  std_logic;
        dsw    : in  std_logic;
        ldtack : in  std_logic;
        d      : out std_logic;
        lds    : out std_logic;
        dtack  : out std_logic
    );
end VME;

architecture stage4 of VME is
    signal U1_ON           : std_logic;
    signal IN_BUBBLE3_ON   : std_logic;
    signal U5_ON           : std_logic;
    signal IN_BUBBLE8_ON   : std_logic;
    signal IN_BUBBLE11_ON  : std_logic;
    signal OUT_BUBBLE14_ON : std_logic;
    signal U15_ON          : std_logic;
    signal IN_BUBBLE17_ON  : std_logic;
    signal IN_BUBBLE19_ON  : std_logic;
    signal IN_BUBBLE21_ON  : std_logic;
    signal U22_ON          : std_logic;
begin

    -- Gate instantiations matching the Verilog netlist
    U1_inst: NAND3
        port map (
            ON => U1_ON,
            A  => ldtack,
            B  => U22_ON,
            C  => dsr
        );
    
    -- This inverter should have a short delay
    IN_BUBBLE3_inst: INV
        port map (
            ON => IN_BUBBLE3_ON,
            I  => OUT_BUBBLE14_ON
        );
    
    U5_inst: OAI21
        port map (
            ON => U5_ON,
            A1 => IN_BUBBLE3_ON,
            A2 => U22_ON,
            B  => dsw
        );
    
    U6_inst: NAND2
        port map (
            ON => d,
            A  => U1_ON,
            B  => U5_ON
        );
    
    -- This inverter should have a short delay
    IN_BUBBLE8_inst: INV
        port map (
            ON => IN_BUBBLE8_ON,
            I  => dsw
        );
    
    U9_inst: AO22
        port map (
            O  => lds,
            A1 => IN_BUBBLE8_ON,
            A2 => U22_ON,
            B1 => dsw,
            B2 => OUT_BUBBLE14_ON
        );
    
    -- This inverter should have a short delay
    IN_BUBBLE11_inst: INV
        port map (
            ON => IN_BUBBLE11_ON,
            I  => OUT_BUBBLE14_ON
        );
    
    U12_inst: AOI21
        port map (
            ON => dtack,
            A1 => dsw,
            A2 => d,
            B  => IN_BUBBLE11_ON
        );
    
    OUT_BUBBLE14_inst: INV
        port map (
            ON => OUT_BUBBLE14_ON,
            I  => U15_ON
        );
    
    U15_inst: AOI222
        port map (
            ON => U15_ON,
            A1 => d,
            A2 => U22_ON,
            B1 => OUT_BUBBLE14_ON,
            B2 => U22_ON,
            C1 => dsw,
            C2 => OUT_BUBBLE14_ON
        );
    
    -- This inverter should have a short delay
    IN_BUBBLE17_inst: INV
        port map (
            ON => IN_BUBBLE17_ON,
            I  => dsr
        );
    
    -- This inverter should have a short delay
    IN_BUBBLE19_inst: INV
        port map (
            ON => IN_BUBBLE19_ON,
            I  => d
        );
    
    -- This inverter should have a short delay
    IN_BUBBLE21_inst: INV
        port map (
            ON => IN_BUBBLE21_ON,
            I  => U22_ON
        );
    
    U22_inst: AOI222
        port map (
            ON => U22_ON,
            A1 => IN_BUBBLE17_ON,
            A2 => IN_BUBBLE19_ON,
            B1 => ldtack,
            B2 => IN_BUBBLE21_ON,
            C1 => dsw,
            C2 => ldtack
        );

    -- Initial signal values (for simulation):
    -- IN_BUBBLE11_ON = '1', IN_BUBBLE17_ON = '1', IN_BUBBLE19_ON = '1'
    -- IN_BUBBLE21_ON = '1', IN_BUBBLE3_ON = '1', IN_BUBBLE8_ON = '1'
    -- OUT_BUBBLE14_ON = '0', U15_ON = '1', U1_ON = '1', U22_ON = '0'
    -- U5_ON = '1', d = '0', dsr = '0', dsw = '0', dtack = '0'
    -- lds = '0', ldtack = '0'

end stage4;